use std::{
    collections::HashMap,
    io::{Read, Write},
    sync::{
        atomic::{AtomicBool, Ordering},
        Arc, Mutex,
    },
};

use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use portable_pty::{CommandBuilder, MasterPty, NativePtySystem, PtySize, PtySystem as _};
use tauri::{AppHandle, Emitter, State};

// ── Shell init polyglot ───────────────────────────────────────────────────────
//
// This string is written verbatim to the PTY master immediately after spawn so
// that the shell's line discipline queues it as stdin before the user's rc
// files finish executing.
//
// Known limitation (rc-file race): the bytes are written before the shell has
// read its rc file, relying on the TTY line discipline to buffer the input until
// the shell is ready. This usually works, but a user's ~/.zshrc that does
// `precmd_functions=()` (bare assignment, not `+=`) would clobber our hook.
// The mitigation is `add-zsh-hook` on zsh (deduplication-safe, append-style)
// and `PROMPT_COMMAND` prepend on bash (safe against user appends, but not
// against outright replacement with bare assignment).
//
// The script:
//   1. Defines __ai_dungeon_emit_ctx() which emits OSC 7 (CWD) and OSC 7337
//      (git context) after every prompt.
//   2. Wires the function into the prompt cycle for bash and zsh.
//   3. Is a single newline-terminated line suitable for piping to a shell stdin.
#[cfg(unix)]
const SHELL_INIT_POLYGLOT: &str = concat!(
    // Define the context-emission function.
    "__ai_dungeon_emit_ctx() {",
    // Emit OSC 7: file://hostname/cwd for the current working directory.
    // Uses ${HOST:-${HOSTNAME}}: zsh exports $HOST, bash exports $HOSTNAME.
    " printf '\\033]7;file://%s%s\\033\\\\' \"${HOST:-${HOSTNAME}}\" \"${PWD}\";",
    // Fast pre-check — exits non-zero immediately outside a git repo (traverses
    // up to first mount point). On network filesystems or very deep trees this
    // may add prompt latency.
    " if git rev-parse --git-dir >/dev/null 2>&1; then",
    // Guard: only emit OSC 7337 with payload when show-toplevel succeeds and is
    // non-empty. When inside a .git directory, --git-dir succeeds but
    // --show-toplevel may fail or return empty.
    "  repo_top=$(git rev-parse --show-toplevel 2>/dev/null);",
    "  if [ -n \"$repo_top\" ]; then",
    "   repo=$(basename \"$repo_top\");",
    "   branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null);",
    "   printf '\\033]7337;%s\\t%s\\033\\\\' \"$repo\" \"$branch\";",
    "  else",
    // Inside a .git directory or bare repo — emit empty payload to clear git context.
    "   printf '\\033]7337;\\033\\\\';",
    "  fi;",
    " else",
    // Not in a git repo — emit empty OSC 7337 payload to clear stale git state.
    "  printf '\\033]7337;\\033\\\\';",
    " fi",
    "}; ",
    // Wire into zsh via add-zsh-hook (deduplication-safe, append-style).
    "if [ -n \"$ZSH_VERSION\" ]; then",
    " autoload -U add-zsh-hook && add-zsh-hook precmd __ai_dungeon_emit_ctx;",
    // Wire into bash by prepending to PROMPT_COMMAND (safe against user appends).
    "elif [ -n \"$BASH_VERSION\" ]; then",
    " PROMPT_COMMAND=\"__ai_dungeon_emit_ctx${PROMPT_COMMAND:+; $PROMPT_COMMAND}\";",
    "fi\n",
);

// ── Session ──────────────────────────────────────────────────────────────────

pub struct PtySession {
    /// The master side of the PTY pair, used for resize.
    master: Arc<Mutex<Box<dyn MasterPty + Send>>>,
    /// The write half of the PTY master, used for input.
    ///
    /// Held behind its own mutex so blocking writes never hold the outer map
    /// lock while `pty_resize` tries to acquire `master`.
    writer: Arc<Mutex<Box<dyn Write + Send>>>,
    /// The spawned child process.
    ///
    /// NOTE: `Box<dyn portable_pty::Child + Send>` — `+ Sync` is NOT required
    /// and WILL fail to compile. Do not add `+ Sync` here.
    child: Arc<Mutex<Box<dyn portable_pty::Child + Send>>>,
    /// Set to `true` by `pty_kill` before resources are dropped. The reader
    /// loop checks this flag after each `read()` to decide whether to continue.
    shutdown: Arc<AtomicBool>,
}

// ── State ─────────────────────────────────────────────────────────────────────

#[derive(Default)]
pub struct PtyState(pub Mutex<HashMap<String, Arc<PtySession>>>);

// ── Commands ──────────────────────────────────────────────────────────────────

/// Open a PTY, spawn the user's default shell, and start streaming output
/// to the frontend via `pty:output:{session_id}` events.
///
/// `session_id` is generated by the frontend (UUID) and must be unique per tab.
#[tauri::command]
pub async fn pty_spawn(
    app: AppHandle,
    state: State<'_, PtyState>,
    session_id: String,
    cols: u16,
    rows: u16,
) -> Result<(), String> {
    let pty_system = NativePtySystem::default();

    let size = PtySize {
        rows,
        cols,
        pixel_width: 0,
        pixel_height: 0,
    };

    let pair = pty_system
        .openpty(size)
        .map_err(|e| format!("openpty failed: {e}"))?;

    // Resolve the default shell.
    #[cfg(unix)]
    let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/bash".into());
    #[cfg(windows)]
    let shell = std::env::var("COMSPEC").unwrap_or_else(|_| "cmd.exe".into());

    let mut cmd = CommandBuilder::new(&shell);
    cmd.env("TERM", "xterm-256color");
    cmd.env("COLORTERM", "truecolor");

    // Use HOME (Unix) / USERPROFILE (Windows) as the initial working directory.
    #[cfg(unix)]
    if let Ok(home) = std::env::var("HOME") {
        cmd.cwd(home);
    }
    #[cfg(windows)]
    if let Ok(profile) = std::env::var("USERPROFILE") {
        cmd.cwd(profile);
    }

    // M-1: Take the writer from the BARE master FIRST, before wrapping master
    // in Arc<Mutex<>>. The writer borrow requires exclusive access to the pair
    // slot; wrapping first would move master before we can call take_writer().
    let writer = pair
        .master
        .take_writer()
        .map_err(|e| format!("take_writer failed: {e}"))?;

    // Now wrap master in Arc<Mutex<>> for shared resize access.
    let master = Arc::new(Mutex::new(pair.master));

    let child = pair
        .slave
        .spawn_command(cmd)
        .map_err(|e| format!("spawn failed: {e}"))?;

    let shutdown = Arc::new(AtomicBool::new(false));

    // M-3: Clone the reader on the calling thread BEFORE inserting the session
    // into the HashMap. If try_clone_reader fails we return Err cleanly without
    // leaking a half-initialised session entry.
    let reader = master
        .lock()
        .map_err(|_| "master mutex poisoned".to_string())?
        .try_clone_reader()
        .map_err(|e| format!("failed to clone reader: {e}"))?;

    let session = Arc::new(PtySession {
        master,
        writer: Arc::new(Mutex::new(writer)),
        child: Arc::new(Mutex::new(child)),
        shutdown: Arc::clone(&shutdown),
    });

    // Insert session; release the outer lock before spawning the reader task.
    state
        .0
        .lock()
        .map_err(|_| "state mutex poisoned".to_string())?
        .insert(session_id.clone(), Arc::clone(&session));

    // Inject the shell init polyglot on Unix so bash/zsh emit OSC 7 (CWD) and
    // OSC 7337 (git context) after every prompt cycle. The bytes are written
    // after session insertion so cleanup (pty_kill) can always find the session.
    // On error we log and proceed — failure to inject does not abort pty_spawn;
    // the terminal still works, just without OSC context updates.
    #[cfg(unix)]
    {
        match session.writer.lock() {
            Ok(mut w) => {
                if let Err(e) = w
                    .write_all(SHELL_INIT_POLYGLOT.as_bytes())
                    .and_then(|_| w.flush())
                {
                    eprintln!("[ai-dungeon] shell init injection failed: {e}");
                }
            }
            Err(_) => {
                eprintln!("[ai-dungeon] shell init injection skipped: writer mutex poisoned");
            }
        }
    }

    // Spawn a blocking thread for the PTY read loop. The reader holds an
    // independent cloned handle — the master mutex remains free for
    // pty_resize to acquire without waiting on a blocked read(). (M-2)
    let app_clone = app.clone();
    let sid = session_id.clone();
    let shutdown_clone = Arc::clone(&shutdown);

    tauri::async_runtime::spawn_blocking(move || {
        let mut buf = [0u8; 4096];
        let mut reader = reader;

        loop {
            match reader.read(&mut buf) {
                Ok(0) => {
                    // EOF — shell exited.
                    let _ = app_clone.emit(&format!("pty:exit:{sid}"), ());
                    break;
                }
                Ok(n) => {
                    if shutdown_clone.load(Ordering::Relaxed) {
                        break;
                    }
                    let encoded = B64.encode(&buf[..n]);
                    let _ = app_clone.emit(&format!("pty:output:{sid}"), encoded);
                }
                Err(_) => {
                    if !shutdown_clone.load(Ordering::Relaxed) {
                        let _ = app_clone.emit(&format!("pty:exit:{sid}"), ());
                    }
                    break;
                }
            }
        }
    });

    Ok(())
}

/// Write base64-encoded bytes to the PTY's input.
///
/// Dispatched off the main thread via `#[tauri::command(async)]`. Plain `fn`
/// commands in Tauri 2 run on the main thread; the `async` annotation moves
/// them to the blocking thread pool.
#[tauri::command(async)]
pub fn pty_write(
    state: State<'_, PtyState>,
    session_id: String,
    data_b64: String,
) -> Result<(), String> {
    // Clone the Arc out of the map; release the outer lock immediately so
    // concurrent resize calls are never serialised behind this write.
    let session = {
        let map = state.0.lock().map_err(|_| "state mutex poisoned")?;
        map.get(&session_id)
            .ok_or_else(|| format!("session not found: {session_id}"))?
            .clone()
    };

    let bytes = B64
        .decode(data_b64.as_bytes())
        .map_err(|e| format!("base64 decode failed: {e}"))?;

    let mut writer = session
        .writer
        .lock()
        .map_err(|_| "writer mutex poisoned")?;

    writer
        .write_all(&bytes)
        .map_err(|e| format!("write failed: {e}"))?;

    writer
        .flush()
        .map_err(|e| format!("flush failed: {e}"))?;

    Ok(())
}

/// Resize the PTY.
///
/// Dispatched off the main thread via `#[tauri::command(async)]`. Plain `fn`
/// commands in Tauri 2 run on the main thread; the `async` annotation moves
/// them to the blocking thread pool.
#[tauri::command(async)]
pub fn pty_resize(
    state: State<'_, PtyState>,
    session_id: String,
    cols: u16,
    rows: u16,
) -> Result<(), String> {
    // Clone the Arc out of the map; release the outer lock before acquiring master.
    let session = {
        let map = state.0.lock().map_err(|_| "state mutex poisoned")?;
        map.get(&session_id)
            .ok_or_else(|| format!("session not found: {session_id}"))?
            .clone()
    };

    let size = PtySize {
        rows,
        cols,
        pixel_width: 0,
        pixel_height: 0,
    };

    session
        .master
        .lock()
        .map_err(|_| "master mutex poisoned")?
        .resize(size)
        .map_err(|e| format!("resize failed: {e}"))?;

    Ok(())
}

/// Kill the PTY session and clean up.
///
/// Returns `Ok(())` if the session is already absent (idempotent).
#[tauri::command]
pub fn pty_kill(state: State<'_, PtyState>, session_id: String) -> Result<(), String> {
    let session = {
        let mut map = state.0.lock().map_err(|_| "state mutex poisoned")?;
        map.remove(&session_id)
    };

    let session = match session {
        Some(s) => s,
        // Session already gone — idempotent, return Ok.
        None => return Ok(()),
    };

    // Signal the reader loop to stop after its next read returns.
    session.shutdown.store(true, Ordering::Relaxed);

    // Kill the child process; ignore AlreadyExited.
    if let Ok(mut child) = session.child.lock() {
        let _ = child.kill();
        // On Unix, a process that exits without being waited becomes a zombie
        // until the parent calls waitpid.
        // `kill()` terminates the child; `wait()` reaps it. `wait()` returns
        // immediately if the child already exited.
        // Reap the child to avoid zombie processes on Unix (POSIX waitpid semantics).
        let _ = child.wait();
    }

    Ok(())
}
